### ISSUE TITLE
翻译错别字

### ISSUE THREAD

**Issue by ZerolAcqua** [jk15162428/hanabi_cn#1]
- 规则
  - 胜利
  >  本游戏并没有胜利条件，当且仅当获取到可以获得的最高分、抽**排**堆为空且所有玩家完成最后一轮或失误3次后游戏立刻结束……
- 提示解读
  - Clue Overview
  > 总**得**来说，现在我们有：
- 巧技
  - 第一个示例
  > Cathy看到在给出红色提示后盲打即刻发生，她知道自己一定有着接下来的牌，那张**洪**4。

**Comment by jk15162428** [comment]
fixed
